export {
  buildConstellationModel,
  buildUnifiedConstellation,
  computeStats,
  ORBIT_GROUPS,
  ODC_NOMINAL_TOTAL,
  ODC_POLAR_NOMINAL_TOTAL,
  ODC_INCLINED_NOMINAL_TOTAL,
  groupNominalBreakdown,
  STARLINK_GEN1_AUTHORIZED,
  STARLINK_GEN1_DEPLOYED_EXTRA,
  STARLINK_GEN1_NOMINAL_AUTHORIZED,
  STARLINK_GEN1_NOMINAL_DEPLOYED,
  starlinkGroupsForMode,
  starlinkShellLabel,
  STARLINK_GEN2_GRANTED,
  STARLINK_GEN2_APPLICATION,
  STARLINK_GEN2_FCC_TRANCHE_CAP,
  STARLINK_GEN2_NOMINAL_APPLICATION,
  STARLINK_GEN2_NOMINAL_GRANTED_MAX,
  GEN1_GEN2_ALTITUDE_GAP_KM,
  starlinkGen2GroupsForMode,
  starlinkGen2ShellLabel,
  STARLINK_DEPLOYED_TOTAL,
  STARLINK_DEPLOYED_GEN1_TOTAL,
  STARLINK_DEPLOYED_GEN2_TOTAL,
  DEPLOYMENT_SNAPSHOT_DATE,
  DEPLOYMENT_SNAPSHOTS,
  deploymentSnapshotById,
  snapshotSourceSummary,
  reconcileDeploymentTotal,
  starlinkGroupsForView,
  starlinkDeployedGroups,
  deployedShellLabel,
  groupLabel,
  formatInclination,
  isPolarGroup,
  isOdcGroup,
  isStarlinkGroup,
  isStarlinkGen1Group,
  isStarlinkGen2Group,
  type ConstellationLayerEntry,
  type ConstellationModel,
  type ConstellationShell,
  type ConstellationStats,
  type LayerStats,
  type TopologyStats,
  type OrbitGroupConfig,
  type StarlinkDeploymentMode,
  type StarlinkGen2Mode,
  type StarlinkGen2Inc365,
  type StarlinkViewMode,
  type UnifiedConstellation,
} from "./model/unifiedConstellation";
